url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

# plugins:
#   - jekyll-postcss
# postcss:
#   cache: false

plugins:
  - jekyll-last-modified-at
last-modified-at:
  date-format: "%y-%m-%d %H:%M:%S"
